// Design: single-file HTML mockups generated by the AI, and the signed links used to preview them.
const crypto = require("crypto");

const DESIGN_KINDS = {
  site: "un site de prezentare cu mai multe secțiuni (hero, servicii, despre, testimoniale, contact, subsol)",
  landing: "o pagină de destinație (landing page) cu un singur obiectiv și un apel la acțiune clar, repetat",
  afis: "un afiș (poster) pe o singură pagină, în format vertical, cu titlu mare și informații esențiale",
  prezentare: "o prezentare cu 6–10 slide-uri 16:9 așezate unul sub altul, fiecare slide ca secțiune separată",
  card: "o carte de vizită (față și verso, proporția 85×55 mm), afișată centrat",
  meniu: "un meniu de restaurant sau cafenea, cu categorii, preparate, descrieri scurte și prețuri",
  cv: "un CV pe o pagină A4, curat, potrivit și pentru tipărire",
  email: "un email HTML de maximum 600px lățime, centrat, cu structură simplă compatibilă cu clienții de email",
  altceva: "designul descris de utilizator"
};
const MAX_VERSIONS = 30;
const PREVIEW_TTL_MS = 15 * 60 * 1000;

function designSystemPrompt(kind) {
  return [
    "Ești designerul AI Stoica. Creezi machete ca UN SINGUR fișier HTML complet și autonom.",
    `Tipul cerut: ${DESIGN_KINDS[kind] || DESIGN_KINDS.altceva}.`,
    "Reguli obligatorii:",
    "- Răspunde DOAR cu documentul HTML, de la <!doctype html> până la </html>, fără explicații înainte sau după.",
    "- Include <meta charset=\"utf-8\">, <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"> și un <title> potrivit.",
    "- Tot CSS-ul stă inline într-un element <style>; fără <link>, foi de stil externe, fonturi externe sau CDN-uri.",
    "- Fără JavaScript extern; JavaScript inline doar dacă este cu adevărat necesar pentru interacțiune.",
    "- Fără imagini externe (inclusiv images.unsplash.com sau alte linkuri): folosește doar SVG inline, gradiente și forme CSS.",
    "- Design responsive (de la telefon la desktop), modern, cu ierarhie vizuală clară, spațiere generoasă și contrast bun.",
    "- Textele sunt în limba română, cu diacritice corecte (ă, â, î, ș, ț), dacă utilizatorul nu cere altă limbă. Folosește conținut realist, nu „Lorem ipsum”."
  ].join("\n");
}

function designMessages(kind, prompt) {
  return [{ role: "system", content: designSystemPrompt(kind) }, { role: "user", content: String(prompt) }];
}

function reviseMessages(kind, prompt, html, instructions) {
  return [
    { role: "system", content: designSystemPrompt(kind) },
    { role: "user", content: String(prompt) },
    { role: "assistant", content: String(html) },
    { role: "user", content: `Modifică designul de mai sus după aceste instrucțiuni:\n${instructions}\n\nPăstrează tot ce nu trebuie schimbat și răspunde cu documentul HTML complet actualizat.` }
  ];
}

// Takes the HTML document out of a model answer (```html fence, any fence holding HTML, or plain text). "" if none.
function extractHtml(text) {
  const s = String(text || "");
  const fence = s.match(/```[ \t]*html[^\n]*\n([\s\S]*?)(?:```|$)/i);
  let body = fence ? fence[1] : "";
  if (!body) {
    const any = s.match(/```[^\n]*\n([\s\S]*?)(?:```|$)/);
    body = any && /<!doctype html|<html[\s>]/i.test(any[1]) ? any[1] : s;
  }
  const start = body.search(/<!doctype html|<html[\s>]/i);
  if (start < 0) return "";
  body = body.slice(start);
  const end = /<\/html\s*>/i.exec(body);
  if (end) body = body.slice(0, end.index + end[0].length);
  body = body.trim();
  if (!/<(body|head|style|main|div|section)[\s>]/i.test(body)) return "";
  return /^<!doctype/i.test(body) ? body : "<!doctype html>\n" + body;
}

function htmlTitle(html) {
  const m = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(String(html || ""));
  return m ? m[1].replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim().slice(0, 120) : "";
}

function previewSignature(secret, userId, designId, v, exp) {
  return crypto.createHmac("sha256", String(secret)).update(`design-preview\n${userId}\n${designId}\n${v}\n${exp}`).digest("base64url");
}
function previewToken(secret, userId, designId, v, now = Date.now()) {
  const exp = now + PREVIEW_TTL_MS;
  return `${exp}.${previewSignature(secret, userId, designId, v, exp)}`;
}
function verifyPreviewToken(secret, token, userId, designId, v, now = Date.now()) {
  const m = /^(\d{10,16})\.([A-Za-z0-9_-]{43})$/.exec(String(token || ""));
  if (!m) return false;
  const exp = Number(m[1]);
  if (!(exp > now) || exp - now > PREVIEW_TTL_MS + 60000) return false;
  const want = Buffer.from(previewSignature(secret, userId, designId, v, exp)), got = Buffer.from(m[2]);
  return want.length === got.length && crypto.timingSafeEqual(want, got);
}

module.exports = { DESIGN_KINDS, MAX_VERSIONS, PREVIEW_TTL_MS, designSystemPrompt, designMessages, reviseMessages, extractHtml, htmlTitle, previewToken, verifyPreviewToken };
